language: ruby
rvm:
- 2.4.1
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rspec
services:
- postgresql
notifications:
  email: false
deploy:
  api_key:
    secure: jaKBSBapuuiy1lJXcS24LO8VtEhUabf7/xvkdZS0oHHXlx7udkdSAlWGEeivRc1XGcVc+VQIlPiOjYQEiq9VR+mpMEz1neWZ8WcuwDgZe6wxDSViOuWk2LHRz4ofsXWQGuNYCGBpjNWRFl52p374sAUsD8WgHj4ZmEXMs0WvRbZO2IE1/4oB7G6E3W+EmAUlZKK5MnI00Hz6oHuHsCeFbq0/3ow7Qdyi/LRt1QOIutBfs52cPsl2Yve3O+ZoDT6TRByzH1AOa1FcBxZo1QXJVbeWmbxAOIqOUwDlzOB9DsStPeQ+GQ/2LByzf2h7JWluroMNaUQfAJkqoA2j6INwQhY7tmK4aIsH3LGAEihuDPQLyJjoXNuhHdQJqxZNPQ/MNbCxx5WrwZBnIsVFP/V6Mb/Ly6RULhZHlEB9z3uylxEXVgTxYsLUWEcFxIV/jyOgi55OaSWo+pBc1mGAe2UVGM9vnUrJanMN262A6gJLWFDswPFJvygzUxl5yo9qUbS8gpKkYCR6itRm38mPyulW6wIhEYMFqP2r3qlTX2ZDp2X/Co1hhS88cxM97R9af5mM45RAxsfkI0DnuVKIq1uib8bjFwq+0u010x3ekcc5+du14BcG2HQpV2I+X5+qpKzK49/Ao+5Iy0fxZg6NmpXMIq+vePNgVaW+DkuVkTtmsKg=
